language: go
go:
  - 1.14
sudo: required

services:
  - docker

script:
  - docker build -t dhawton/staticserve .

deploy:
  provider: script
  skip_cleanup: true
  script:
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && \
    docker tag dhawton/staticserve dhawton/staticserve:$TRAVIS_TAG && \
    docker push dhawton/staticserve:$TRAVIS_TAG
  on:
    branch: master
    tags: true