os: linux
dist: xenial

services:
  - docker

script:
  - docker build -t dhawton/staticserve .

after_success:
  - if [ "$TRAVIS_TAG" != "" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag dhawton/staticserve dhawton/staticserve:$TRAVIS_TAG;
    docker push dhawton/staticserve:$TRAVIS_TAG;
    fi